name: tictok_clone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  font_awesome_flutter: 10.3.0
  video_player: ^2.8.7
  visibility_detector: ^0.4.0+2
  chewie: ^1.8.1
  go_router: ^14.2.0
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  gallery_saver: 2.3.2
  image_picker: 0.8.6+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/video.mp4
    - assets/images/placeholder.jpg
